### ISSUE TITLE
failed to connect websocket

### ISSUE THREAD

**Issue by DmitriBelski** [negi-grass/crypto-botters#24]
Hi, Negi-grass!

I got this error, related to Secure Socket Layer

`thread 'main' panicked at 'failed to connect websocket: Tls(Native(Ssl(Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 336130315, library: "SSL routines", function: "ssl3_get_record", reason: "wrong version number", file: "../ssl/record/ssl3_record.c", line: 331 }]))) }, X509VerifyResult { code: 0, error: "ok" })))', src/main.rs:17:11`

this is my main.rs

```
use std::time::Duration;
use log::LevelFilter;
use env_logger;
use crypto_botters::{binance::{BinanceOption, BinanceWebSocketUrl}, Client};

#[tokio::main]
async fn main() {
  env_logger::builder()
    .filter_level(LevelFilter::Debug)
    .init();
  let client = Client::new();

  let connection = client.websocket(
    "/ws/btcusdt@ticker",
    |message| println!("{}", message),
    [BinanceOption::WebSocketUrl(BinanceWebSocketUrl::Spot9443)],
  ).await.expect("failed to connect websocket");
  tokio::time::sleep(Duration::from_secs(1)).await;

  connection.reconnect_state().request_reconnect();

  tokio::time::sleep(Duration::from_secs(3)).await;

  drop(connection);

  tokio::time::sleep(Duration::from_secs(1)).await;
}
```
What can I do with it?

**Comment by negi-grass** [comment]
I've tested your code on my computer and it seems to have no problem.

Probably something had gone wrong in OpenSSL installed in your environment. There are many possible causes of this error, according to information on the internet, so I don't think I can help you with the your OpenSSL error.

Instead, I've released v0.4.3 of this crate today, which adds Cargo features that allows you to use different libraries for TLS connection.

Try each of the below in your `Cargo.toml` and see if any of them solves your problem.

## default(native-tls)
This uses native-tls (SChannel on Windows, Secure Transport on OSX, and OpenSSL on other platforms).
This was the only choise under v0.4.2.
```
[dependencies]
crypto-botters = { version = "0.4.3", features = ["binance"] }
```

## native-tls-vendored
Same as native-tls, except that a copy of OpenSSL is used instead of OpenSSl installed in your environment. C, perl and make is required for build.
```
[dependencies]
crypto-botters = { version = "0.4.3", default-features = false, features = ["binance", "native-tls-vendored"] }
```

## rustls-tls-native-roots
Uses rustls and certificates from your platform’s native certificate store.
```
[dependencies]
crypto-botters = { version = "0.4.3", default-features = false, features = ["binance", "rustls-tls-native-roots"] }
```

## rustls-tls-webpki-roots
Uses rustls and Mozilla's root certificates.
```
[dependencies]
crypto-botters = { version = "0.4.3", default-features = false, features = ["binance", "rustls-tls-webpki-roots"] }
```

**Comment by DmitriBelski** [comment]
Thank you for your suggestions!
First two gave the same result as before, but last two gave this new error
```
[2023-03-02T21:58:26Z DEBUG rustls::client::hs] No cached session for DnsName(DnsName(DnsName("stream.binance.com")))
[2023-03-02T21:58:26Z DEBUG rustls::client::hs] Not resuming any session
thread 'main' panicked at 'failed to connect websocket: Io(Custom { kind: InvalidData, error: CorruptMessage })', src/main.rs:17:11
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
this is related to the OpenSSL installed on my machine? Or maybe I need get some cert from binance side?

**Comment by negi-grass** [comment]
> this is related to the OpenSSL installed on my machine? Or maybe I need get some cert from binance side?

No, the first two options use OpenSSL (if you are on Linux) and the last two options use a different library, [rustls](https://github.com/rustls/rustls).

Using the last option in my environment, the messeage is like the following:
```
[2023-03-03T00:20:21Z DEBUG rustls::client::hs] No cached session for DnsName(DnsName(DnsName("stream.binance.com")))
[2023-03-03T00:20:21Z DEBUG rustls::client::hs] Not resuming any session
[2023-03-03T00:20:21Z DEBUG rustls::client::hs] ALPN protocol is None
[2023-03-03T00:20:21Z DEBUG rustls::client::hs] Using ciphersuite TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
[2023-03-03T00:20:21Z DEBUG rustls::client::tls12::server_hello] Server supports tickets
[2023-03-03T00:20:21Z DEBUG rustls::client::tls12] ECDHE curve is ECParameters { curve_type: NamedCurve, named_group: secp256r1 }
[2023-03-03T00:20:21Z DEBUG rustls::client::tls12] Server DNS name is DnsName(DnsName(DnsName("stream.binance.com")))
[2023-03-03T00:20:21Z DEBUG rustls::client::tls12] Session saved
[2023-03-03T00:20:21Z DEBUG tungstenite::handshake::client] Client handshake done.
[2023-03-03T00:20:21Z DEBUG generic_api_client::websocket] WebSocket connection started
{"A":"0.01249000","B":"0.00150000","C":1677802823317,"E":1677802823318,"F":2850969444,"L":2858337418,"O":1677716423317,"P":"-1.237","Q":"0.00110000","a":"23436.52000000","b":"23435.80000000","c":"23436.54000000","e":"24hrTicker","h":"23796.93000000","l":"23195.90000000","n":7367975,"o":"23730.02000000","p":"-293.48000000","q":"5535763532.16037230","s":"BTCUSDT","v":"236457.27209000","w":"23411.26362167","x":"23729.45000000"}
```

Have you ever successfully connected to Binance WebSocket using other libraries?

Given that neither OpenSSL nor rustls were successful, I suspect that there is a problem in your environment.

**Comment by negi-grass** [comment]
Closing this issue as the author @DmitriBelski  is not responding.

If anyone encounters a similar issue in the future, please open a new issue.
