### ISSUE TITLE
How to use proxy in http or websocket

### ISSUE THREAD

**Issue by Tindtily** [negi-grass/crypto-botters#88]
As subject

**Comment by negi-grass** [comment]
Currently, this library does not include code that is specifically for supporting proxies. However, for HTTP(S) connections, system proxies (env variables like `HTTP_PROXY` and `HTTPS_PROXY`) are [supported by the underlying `reqwest` library by default](https://docs.rs/reqwest/latest/reqwest/index.html#proxies). Proxies are not supported on WebSocket connections as [they are not supported by the underlying tungstenite-rs library](https://github.com/snapview/tungstenite-rs/issues/177).
